### ISSUE TITLE
So Very Easy Installer 

### ISSUE THREAD

**Issue by happyconcepts** [happyconcepts/eos-indicator#3]
Installer for the non-dev crowd would be sublime. 

Paging @bradheff could I get access to TestProject to make an easy installer?

**Comment by BradHeff** [comment]
> Installer for the non-dev crowd would be sublime.
> 
> Paging @BradHeff could I get access to TestProject to make an easy installer?

Yeh sorry i removed it a while ago, just uploaded it again you should have access here

https://github.com/BradHeff/TestProject

**Comment by happyconcepts** [comment]
Such appreciation!
